# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 484c1b8c61edb2ae7e202dd58ddfd34e5b72bc3e18f6f1bcff05b236cb67c2665e7a17147bbfd1332934b1a668884ebf44602427b58a77e9fc67935062415cf8

test:
  secret_key_base: feae7e9ff3ceeee958ec318c603b2bf6959d443a7c2feb50fc91d9207abed9d8ea6eb7b8fcc0a1b4e3ad1651604e4afb1e99586608bfbb716f6ed837e20e22c2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
